### PR TITLE
plugin `--clusterio-modules` option

### PR DESCRIPTION
**Pull request by JanSharp**
This is an extension of the #121 PR, adding the `--clustorio-modules` option and documentation for plugin args in general (so also adding docs for `--ignore` which is unrelated).

This is the simple implementation for an argument to support this. There is the other implementation here: #125 
To compare the 2:

This simple implementation is, well, simple, definitely bug free and ultimately also user friendly. Many upsides. The only downside is that it is not configurable, so it is single purpose and that's it.

The other implementation is complex enough to potentially still contain some bug, which is fine. It enables anybody to modify require module paths however they want... within the limits of Lua patterns at least. With the additional feature of being able to mark given regions of text within the require paths to remain untouched (also specified by lua patterns). This is quite nice as it both covers the usage for clustorio, while also allowing anybody else to benefit from it if needed.

The big issue is however that there is no good way of validating Lua patterns, so there are 2 pcalls and 3 warnings inside of the custom gsub logic - said warnings are popups in the bottom right in vscode. Not only is this not clean but it's also not the best user experience. The way the `keep` arguemnt works may not be intuitive either.

I think that just about covers the pros and cons of both implementations. Even though I've spent the time to implement the gsub and keep options, I'm actually leaning more towards using simple implementation in this PR here, but I'm not certain so I wanted to present both options.

### CODE REVIEW

**Comment by justarandomgeek** [comment]
thank you for doing the work to evaluate both options here - i want to actually try both flavors a bit to see the UX myself but just from cursory review i'm pretty sure i agree with your conclusion that this simpler one is better for now!

**Comment by justarandomgeek** [comment]
no amount of fiddling seems to make this combination of options work (even after the spelling fix):
```json
"Lua.runtime.pluginArgs": [
        "--clusterio-modules",
        "--ignore", ".vscode/bar.lua",
    ]
```
whether the ignore is before or after

**Comment by JanSharp** [comment]
I've tested it and it appears to be working. The arg parser is definitely working, and the ignore feature is "working as intended". Though looking at the changelog entires you've added I think my description for what it does is poor, does this make more sense?
```
Completely disable the plugin for the given folders or files.
Either absolute or relative to the workspace root.
```
It's completely unrelated to any plugin module: If any file's normalized absolute path starts with any of the provided `--ignore` options (which get normalized into absolute paths) then that file does not get processed by the plugin at all.
It's a feature that's been in the plugin for a long time, it was just hidden because the arg parser was terrible and the feature kept breaking due to internal changes in the language server. This version now appears to be stable though, hopefully it stays that way.

(It's this logic here: https://github.com/justarandomgeek/vscode-factoriomod-debug/pull/126/files#diff-431b76fa112725845eb0d2ae9f66d16dc68fca993d2b9b70f4cc2a0f5897a8fbR100-R123 )

**Comment by justarandomgeek** [comment]
Ah yes, i guess i misread what the ignore does. i'll adjust that...

When i try to set both settings as shown above (in either order), i just get this in the output:
```
[Warn  - 8:39:11 AM] Invalid plugin args: Unknown/too many values. See Output/log for help message.
[Warn  - 8:39:11 AM] Unknown/too many values.

    [--ignore <string[]>]             Ignore the given files entirely.
    [--clusterio-modules]             Enable the require module path modification for
                                      "^modules/[^/]-/" to get replaced with "module/",
                                      except for "^modules/clusterio/" which remains untouched.
    [-h | --help]                     Show help message.
```

**Comment by justarandomgeek** [comment]
either of the two settings works individually though

**Comment by JanSharp** [comment]
Oh no... "works on my machine"... I'll think about it more, test a bit more, but I currently got nothing.
I'll also adjust the description for `--ignore` because I noticed that the help message does not match what I put in the docs (and they're supposed to be basically copy paste)

**Comment by JanSharp** [comment]
Actually do you have `Lua.runtime.pluginArgs` in both the user and workspace settings? I wonder if it's combining them (if you do have both)

**Comment by JanSharp** [comment]
Alright sorry for the many small messages and commits, but could you try this version again? Mainly curious about 2 things:
1) if the right version of the plugin is actually being loaded and run (which we would see if the error message you're getting is different now)
2) what numbers it's reporting (if the right version is being run - it probably is)

**Comment by justarandomgeek** [comment]
I think the confusion about `ignore` was mostly just me trying to describe things at almost midnight after a rapid context switch!

> Actually do you have `Lua.runtime.pluginArgs` in both the user and workspace settings? I wonder if it's combining them (if you do have both)

I'm setting it in workspace, and just doubled checked that i dont' have one set in user

> if the right version of the plugin is actually being loaded and run (which we would see if the error message you're getting is different now)
> what numbers it's reporting (if the right version is being run - it probably is)

with the `--clusterio-modules` option first, i get:

```
[Warn  - 2:29:02 PM] Invalid plugin args: Unknown/too many values. Consumed 0 out of 15 arguments. See Output/log for help message.
[Warn  - 2:29:02 PM] Unknown/too many values. Consumed 0 out of 15 arguments.
```

but if i move it to last, it is 19 instead of 15.

notably 15 and 19 are string lengths of the clusterio option and the test path i used, which suggests you got that somewhere instead of an array length?!?

**Comment by justarandomgeek** [comment]
perhaps we should log the received/parsed args all the time?

**Comment by justarandomgeek** [comment]
huh. I'm pretty sure LuaLS is mangling something before it gets here...

i put 
```lua
do
  local sargs = {}
  for _, x in ipairs({...}) do
    sargs[#sargs+1] = tostring(x)
  end
client.logMessage("Info", "Received args: " .. table.concat(sargs, " "))
end
```
near where you've got the selects out of `...`

and got...

`[Info  - 3:04:23 PM] Received args: function: 0000021E50E89590 file:///c%3A/Users/Echo/AppData/Roaming/Factorio/mods --clusterio-modules`

which seems to only include the last arg!

**Comment by JanSharp** [comment]
Yea that explains it... but looking at the LuaLS source, the last changes were 5 months ago where they added multi plugin support, and we're both on versions past that point. There's just a few too many internals involved when it fetches the config/settings for me to confiendtly determine what's wrong in there, but it's incredibly odd for it to work for me and not for you. So I'm still confused :thinking:

**Comment by JanSharp** [comment]
Oh no I think I see it is there, by chance, a number in your config path? If you're using the third party setting with apply in memory (which I'm not) then you do have numbers in the path since it contains a guid.
And there's this code here: https://github.com/LuaLS/lua-language-server/blob/85cb44556575f81a31267fe3c443822f3e97699e/script/plugin.lua#L158-L166 which ends up running a `string.find` where `k` is a number

**Comment by justarandomgeek** [comment]
you mean `C:\Users\Echo\AppData\Roaming\Code - Insiders\User\workspaceStorage\674a9ea7afd7b0e3f6f94b3463fd49b4\justarandomgeek.factoriomod-debug\sumneko-3rd\factorio\config.json` ? the folder ends up with a number in it anyway since it's still called `sumneko-3rd` too

**Comment by JanSharp** [comment]
Yea exactly that path. I'm making a PR right now that should fix this. It's a simple extra check in an if condition not to try to match array keys with workspace path names.

**Comment by JanSharp** [comment]
I think what you can do is use this and it'll work for you. We may want to suggest/advertise that pattern anyway actually
```json
    "Lua.runtime.pluginArgs": {
        "factorio": [
            "--clusterio-modules",
            "--ignore", ".vscode/bar.lua",
        ],
    },

**Comment by justarandomgeek** [comment]
doing that seems to get only `{"factorio"}` as the args table

**Comment by JanSharp** [comment]
AAA, and here I thought I understood what the language server was doing. Yea I can't get that to work at all right now either. And the setting type definition makes no sense either. It says it's either an array of strings or a hash of string => string... which should be string => string array... but even putting a string => string into my args doesn't give the value, only the key even though the key should match the config path.

I'm sorry but I'm kind of out of ideas at the moment. The only thing I can say for certain is that the plugin works, it's just something weird in the LS that's not working...

**Comment by JanSharp** [comment]
For continuity I'll put a link to the PR I made here: https://github.com/LuaLS/lua-language-server/pull/2716

**Comment by justarandomgeek** [comment]
they've always had some trouble with consistency between the json type defs and actual lua config types

**Comment by JanSharp** [comment]
Hmm, good call, that would make sense

**Comment by justarandomgeek** [comment]
hmm. debating waiting on LuaLS 3.9.4 for this or going ahead and merging it now with a note that multiple args just won't work until then...

**Comment by JanSharp** [comment]
Yea I was also thinking about waiting on LuaLS. If you do want to merge i now I'd have to adjust it slightly to actually accept a string instead of a string array. Maybe it should accept that anyway since some people may not immediately update the LS

**Comment by JanSharp** [comment]
I've added logic to handle any plugin args the language server could throw our way. With that I'd say it is mergable.

I've also changed the `--ignore` changelog entry to make it more distinct and more verbose. Hope that's alright.

**Comment by justarandomgeek** [comment]
I've gone ahead and merged this with a caveat in the changelog about LuaLS 3.9.3 not currently passing more than one arg properly, since one arg will still meet the needs of the original ask, and more is just waiting on upstream at this point

**Pull request merged**
